# .github/workflows/ci.yml

name: Flask CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Flask App Tests
      run: |
        python -m unittest discover -s tests

    - name: Start Flask app (for testing purposes)
      run: |
        nohup python app.py &

    - name: Ensure Flask app is running (curl test)
      run: |
        sleep 5  # Wait for the app to start
        curl -f http://localhost:5000/  # Test if Flask app is running

    - name: Stop Flask app
      run: |
        pkill -f 'python app.py'  # Stop Flask app after test
